bdf.c: fix the build against -std=c23
`gcc-15` switched to `c23` by default and `bdf2tff`
started to fail the build as:

````
src/bdf.c:131:1: error: conflicting types for 'glyph_open'; have 'bdf_glyph_t *(int,  int)' {aka 'struct _bdf_glyph_t *(int,  int)'}
  131 | glyph_open(int width, int height)
      | ^~~~~~~~~~
src/bdf.c:60:25: note: previous declaration of 'glyph_open' with type 'bdf_glyph_t *(void)' {aka 'struct _bdf_glyph_t *(void)'}
   60 | static bdf_glyph_t*     glyph_open();
      |                         ^~~~~~~~~~
````

THe change fixed explicit prototype for a forward declaration.